// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mods} from '../models';
import {updater} from '../models';
import {app} from '../models';
import {config} from '../models';
import {news} from '../models';

export function CheckInstanceModUpdates(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function CheckLatestNeedsUpdate(arg1:string):Promise<boolean>;

export function CheckModUpdates():Promise<Array<mods.Mod>>;

export function CheckUpdate():Promise<updater.Asset>;

export function CheckVersionAvailability():Promise<app.VersionCheckInfo>;

export function DeleteGame(arg1:string,arg2:number):Promise<boolean>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function DownloadVersion(arg1:string,arg2:string):Promise<void>;

export function ExitGame():Promise<void>;

export function GetAuthDomain():Promise<string>;

export function GetAutoUpdateLatest():Promise<boolean>;

export function GetAvailableVersions():Promise<Record<string, number>>;

export function GetConfig():Promise<config.Config>;

export function GetCrashReports():Promise<Array<app.CrashReport>>;

export function GetCurrentVersion():Promise<string>;

export function GetCustomInstanceDir():Promise<string>;

export function GetGameLogs():Promise<string>;

export function GetGamePath():Promise<string>;

export function GetInstalledMods():Promise<Array<mods.Mod>>;

export function GetInstalledVersions():Promise<Array<app.InstalledVersion>>;

export function GetInstalledVersionsForBranch(arg1:string):Promise<Array<number>>;

export function GetInstanceInstalledMods(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<string>;

export function GetModCategories():Promise<Array<mods.ModCategory>>;

export function GetModDetails(arg1:number):Promise<mods.CurseForgeMod>;

export function GetModFiles(arg1:string,arg2:number,arg3:number):Promise<Array<mods.ModFile>>;

export function GetMusicEnabled():Promise<boolean>;

export function GetNews(arg1:number):Promise<Array<news.NewsItem>>;

export function GetNick():Promise<string>;

export function GetOnlineMode():Promise<boolean>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetSelectedVersion():Promise<number>;

export function GetVersionList(arg1:string):Promise<Array<number>>;

export function GetVersionType():Promise<string>;

export function GetVersions():Promise<string|string>;

export function InstallMod(arg1:number):Promise<void>;

export function InstallModFile(arg1:number,arg2:number):Promise<void>;

export function InstallModFileToInstance(arg1:string,arg2:string,arg3:string,arg4:number):Promise<boolean>;

export function InstallModToInstance(arg1:number,arg2:string,arg3:number):Promise<void>;

export function IsGameInstalled():Promise<boolean>;

export function IsGameRunning():Promise<boolean>;

export function IsVersionInstalled(arg1:string,arg2:number):Promise<boolean>;

export function OpenFolder():Promise<void>;

export function OpenGameFolder():Promise<void>;

export function OpenInstanceModsFolder(arg1:string,arg2:number):Promise<void>;

export function OpenInstanceFolder(arg1:string,arg2:number):Promise<void>;

export function OpenModsFolder():Promise<void>;

export function QuickLaunch():Promise<void>;

export function RepairInstallation():Promise<void>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveConfig():Promise<void>;

export function SaveDiagnosticReport():Promise<string>;

export function SearchMods(arg1:string,arg2:number,arg3:number,arg4:Array<string>,arg5:number,arg6:number):Promise<mods.SearchResult>;

export function SelectInstanceDirectory():Promise<string>;

export function SetInstanceDirectory(arg1:string):Promise<string>;

export function SetAuthDomain(arg1:string):Promise<void>;

export function SetAutoUpdateLatest(arg1:boolean):Promise<void>;

export function SetCustomInstanceDir(arg1:string):Promise<void>;

export function SetMusicEnabled(arg1:boolean):Promise<boolean>;

export function GetUUID():Promise<string>;

export function SetUUID(arg1:string):Promise<boolean>;
export function SetNick(arg1:string):Promise<void>;

export function SetOnlineMode(arg1:boolean):Promise<void>;

export function SetSelectedVersion(arg1:number):Promise<void>;

export function SetVersionType(arg1:string):Promise<void>;

export function SwitchVersion(arg1:number):Promise<void>;

export function ToggleInstanceMod(arg1:string,arg2:boolean,arg3:string,arg4:number):Promise<void>;

export function ToggleMod(arg1:string,arg2:boolean):Promise<void>;

export function UninstallInstanceMod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UninstallMod(arg1:string):Promise<void>;

export function Update():Promise<void>;

export function GetRecentLogs(arg1?:number):Promise<Array<string>>;
