// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mods} from '../models';
import {updater} from '../models';
import {app} from '../models';
import {config} from '../models';
import {news} from '../models';

export function CheckInstanceModUpdates(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function CheckLatestNeedsUpdate(arg1:string):Promise<boolean>;

export interface UpdateInfo {
    OldVersion: number;
    NewVersion: number;
    HasOldUserData: boolean;
    Branch: string;
}

export function GetPendingUpdateInfo(arg1:string):Promise<UpdateInfo|null>;

export function CopyUserData(arg1:string,arg2:number,arg3:number):Promise<boolean>;

export function CheckModUpdates():Promise<Array<mods.Mod>>;

export function CheckUpdate():Promise<updater.Asset>;

export function CheckVersionAvailability():Promise<app.VersionCheckInfo>;

export function CancelDownload():Promise<boolean>;

export function DeleteGame(arg1:string,arg2:number):Promise<boolean>;

export function DownloadAndLaunch(arg1:string):Promise<void>;

export function DownloadVersion(arg1:string,arg2:string):Promise<void>;

export function ExitGame():Promise<void>;

export function GetAuthDomain():Promise<string>;

export function GetAutoUpdateLatest():Promise<boolean>;

export function GetAvailableVersions():Promise<Record<string, number>>;

export function GetConfig():Promise<config.Config>;

export function GetCrashReports():Promise<Array<app.CrashReport>>;

export function GetCurrentVersion():Promise<string>;

export function GetCustomInstanceDir():Promise<string>;

export function GetGameLogs():Promise<string>;

export function GetGamePath():Promise<string>;

export function HasAssetsZip(arg1:string,arg2:number):Promise<boolean>;

export function GetAssetsZipPath(arg1:string,arg2:number):Promise<string|null>;

export function GetInstalledMods():Promise<Array<mods.Mod>>;

export function GetInstalledVersions():Promise<Array<app.InstalledVersion>>;

export function GetInstalledVersionsForBranch(arg1:string):Promise<Array<number>>;

export function GetInstanceInstalledMods(arg1:string,arg2:number):Promise<Array<mods.Mod>>;

export function GetLauncherVersion():Promise<string>;

export function GetLogs():Promise<string>;

export function GetModCategories():Promise<Array<mods.ModCategory>>;

export function GetModDetails(arg1:number):Promise<mods.CurseForgeMod>;

export function GetModFiles(arg1:string,arg2:number,arg3:number):Promise<Array<mods.ModFile>>;

export function GetMusicEnabled():Promise<boolean>;

export function GetNews(arg1:number):Promise<Array<news.NewsItem>>;

export function GetNick():Promise<string>;

export function GetAvatarPreview():Promise<string|null>;

export function GetAvatarPreviewForUUID(uuid:string):Promise<string|null>;

export function ClearAvatarCache():Promise<boolean>;

// Profile Management
export interface Profile {
    id: string;
    uuid: string;
    name: string;
    createdAt: string;
}

export function GetProfiles():Promise<Profile[]>;

export function GetActiveProfileIndex():Promise<number>;

export function CreateProfile(name:string, uuid:string):Promise<Profile|null>;

export function DeleteProfile(profileId:string):Promise<boolean>;

export function SwitchProfile(index:number):Promise<boolean>;

export function UpdateProfile(profileId:string, newName:string|null, newUuid:string|null):Promise<boolean>;

export function SaveCurrentAsProfile():Promise<Profile|null>;

export function GetOnlineMode():Promise<boolean>;

export function GetPlatformInfo():Promise<Record<string, string>>;

export function GetSelectedVersion():Promise<number>;

export function GetVersionList(arg1:string):Promise<Array<number>>;

export function GetVersionType():Promise<string>;

export function GetVersions():Promise<string|string>;

export function InstallMod(arg1:number):Promise<void>;

export function InstallModFile(arg1:number,arg2:number):Promise<void>;

export function InstallModFileToInstance(arg1:string,arg2:string,arg3:string,arg4:number):Promise<boolean>;

export function InstallModToInstance(arg1:number,arg2:string,arg3:number):Promise<void>;

export function InstallLocalModFile(arg1:string,arg2:string,arg3:number):Promise<boolean>;

export function InstallModFromBase64(arg1:string,arg2:string,arg3:string,arg4:number):Promise<boolean>;

export function ExportModList(arg1:string,arg2:number):Promise<string|null>;

export function ExportModsToFolder(arg1:string,arg2:number,arg3:string,arg4:string):Promise<string|null>;

export function GetLastExportPath():Promise<string>;

export function ImportModList(arg1:string,arg2:string,arg3:number):Promise<number>;

export function IsGameInstalled():Promise<boolean>;

export function IsGameRunning():Promise<boolean>;

export function IsVersionInstalled(arg1:string,arg2:number):Promise<boolean>;

export function OpenFolder():Promise<void>;

export function OpenGameFolder():Promise<void>;

export function OpenInstanceModsFolder(arg1:string,arg2:number):Promise<void>;

export function OpenInstanceFolder(arg1:string,arg2:number):Promise<void>;

export function ExportInstance(arg1:string,arg2:number):Promise<string|null>;

export interface InstalledVersionInfo {
    Version: number;
    Branch: string;
    Path: string;
    UserDataSize: number;
    HasUserData: boolean;
}

export function GetInstalledVersionsDetailed():Promise<Array<InstalledVersionInfo>>;

export function OpenModsFolder():Promise<void>;

export function QuickLaunch():Promise<void>;

export function RepairInstallation():Promise<void>;

export function RunDiagnostics():Promise<app.DiagnosticReport>;

export function SaveConfig():Promise<void>;

export function SaveDiagnosticReport():Promise<string>;

export function SearchMods(arg1:string,arg2:number,arg3:number,arg4:Array<string>,arg5:number,arg6:number):Promise<mods.SearchResult>;

export function SelectInstanceDirectory():Promise<string>;

export function BrowseFolder(arg1?:string|null):Promise<string|null>;

export function BrowseModFiles():Promise<string[]>;

export function SetInstanceDirectory(arg1:string):Promise<string>;

export function SetAuthDomain(arg1:string):Promise<void>;

// Skin configuration types and functions
export interface SkinConfig {
    name?: string;
    bodyCharacteristic?: string;
    cape?: string;
    earAccessory?: string;
    ears?: string;
    eyebrows?: string;
    eyes?: string;
    eyeColor?: string;
    face?: string;
    faceAccessory?: string;
    facialHair?: string;
    gloves?: string;
    haircut?: string;
    hairColor?: string;
    headAccessory?: string;
    mouth?: string;
    overpants?: string;
    overtop?: string;
    pants?: string;
    shoes?: string;
    skinFeature?: string;
    skinColor?: string;
    undertop?: string;
    underwear?: string;
    colors?: Record<string, string>;
}

export function GetSkinConfig():Promise<SkinConfig|null>;

export function SaveSkinConfig(arg1:SkinConfig):Promise<boolean>;

export function GetInstanceSkinConfig(arg1:string,arg2:number):Promise<SkinConfig|null>;

export function ApplySkinToInstance(arg1:string,arg2:number):Promise<boolean>;

export function SetAutoUpdateLatest(arg1:boolean):Promise<void>;

export function SetCustomInstanceDir(arg1:string):Promise<void>;

export function SetMusicEnabled(arg1:boolean):Promise<boolean>;

export function GetUUID():Promise<string>;

export function SetUUID(arg1:string):Promise<boolean>;
export function SetNick(arg1:string):Promise<void>;

export function SetOnlineMode(arg1:boolean):Promise<void>;

export function SetSelectedVersion(arg1:number):Promise<void>;

export function SetVersionType(arg1:string):Promise<void>;

export function SwitchVersion(arg1:number):Promise<void>;

export function ToggleInstanceMod(arg1:string,arg2:boolean,arg3:string,arg4:number):Promise<void>;

export function ToggleMod(arg1:string,arg2:boolean):Promise<void>;

export function UninstallInstanceMod(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UninstallMod(arg1:string):Promise<void>;

export function Update():Promise<void>;

export function GetRecentLogs(arg1?:number):Promise<Array<string>>;

export function GetLauncherBranch():Promise<string>;

export function SetLauncherBranch(arg1:string):Promise<boolean>;

export interface RosettaStatus {
    NeedsInstall: boolean;
    Message: string;
    Command: string;
    TutorialUrl?: string;
}

export function CheckRosettaStatus():Promise<RosettaStatus | null>;

// Close after launch setting
export function GetCloseAfterLaunch():Promise<boolean>;
export function SetCloseAfterLaunch(arg1:boolean):Promise<boolean>;

// Discord announcements settings
export function GetShowDiscordAnnouncements():Promise<boolean>;
export function SetShowDiscordAnnouncements(arg1:boolean):Promise<boolean>;
export function DismissAnnouncement(arg1:string):Promise<boolean>;
export function ReactToAnnouncement(arg1:string, arg2:string):Promise<boolean>;

export interface DiscordAnnouncement {
    Id: string;
    Content: string;
    AuthorName: string;
    AuthorAvatar?: string;
    AuthorRole?: string;
    RoleColor?: string;
    ImageUrl?: string;
    Timestamp: string;
}

export function GetDiscordAnnouncement():Promise<DiscordAnnouncement | null>;
// Launcher folder management
export function OpenLauncherFolder():Promise<void>;
export function DeleteLauncherData():Promise<boolean>;
export function GetLauncherFolderPath():Promise<string>;

// Developer testing
export function GetTestAnnouncement():Promise<DiscordAnnouncement | null>;

// News settings
export function GetDisableNews():Promise<boolean>;
export function SetDisableNews(arg1:boolean):Promise<boolean>;

// Background settings
export function GetBackgroundMode():Promise<string>;
export function SetBackgroundMode(arg1:string):Promise<boolean>;
export function GetAvailableBackgrounds():Promise<string[]>;

// Accent color settings
export function GetAccentColor():Promise<string>;
export function SetAccentColor(arg1:string):Promise<boolean>;

// Launcher Data Directory
export function GetLauncherDataDirectory():Promise<string>;
export function SetLauncherDataDirectory(arg1:string):Promise<string|null>;

// Onboarding
export function GetHasCompletedOnboarding():Promise<boolean>;
export function SetHasCompletedOnboarding(arg1:boolean):Promise<boolean>;
export function GetRandomUsername():Promise<string>;
export function ResetOnboarding():Promise<boolean>;

// Game language settings
export function SetGameLanguage(arg1:string):Promise<boolean>;
export function GetAvailableGameLanguages():Promise<string[]>;

// Window controls
export function WindowClose():Promise<void>;